DjangoPet/DjangoPet/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls")),
    path("users/", include("users.urls")),
    path("pets/", include("pets.urls")),
    # path("appointments", include("appointments.urls")),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

DjangoPet/core/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
]

DjangoPet/pets/urls.py
from django.urls import path

from pets.views import MascotaListView, MascotaDetailView

app_name = "pets"

urlpatterns = [
    path("mascotas/", MascotaListView.as_view(), name="mascota_list"),
    path("mascotas/<int:pk>/", MascotaDetailView.as_view(), name="mascota_detail"),
]

DjangoPet/users/urls.py
from django.urls import path

from users.views.veterinario import (
    VeterinarioListView,
    VeterinarioDetailView,
    VeterinarioCreateView,
)

app_name = "users"

urlpatterns = [
    path("veterinarios/", VeterinarioListView.as_view(), name="veterinario_list"),
    path(
        "veterinarios/create/",
        VeterinarioCreateView.as_view(),
        name="veterinario_create",
    ),
    path(
        "veterinarios/<int:pk>/",
        VeterinarioDetailView.as_view(),
        name="veterinario_detail",
    ),
]

DjangoPet/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <title>Django Pet - {% block title %}{% endblock %}</title>
    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet"/>
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'css/styles.css' %}" rel="stylesheet"/>
</head>
<body>
<!-- Responsive navbar-->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container px-5">
        <a class="navbar-brand" href="{% url 'admin:index' %}">Admin</a>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span
                class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'index' %}">Home</a>
                </li>
                <li class="nav-item"><a class="nav-link" href="{% url 'users:veterinario_list' %}">Veterinarios</a></li>
                {% if request.user.is_authenticated %}
                    {% if request.user.is_staff or request.user.is_superuser %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'pets:mascota_list' %}">Mascotas</a>
                    </li>
                    <li class="nav-item"><a class="nav-link" href="#!">Consultas</a></li>
                    {% endif %}
                {% endif %}


            </ul>
        </div>
    </div>
</nav>
<!-- Header-->
<header class="bg-dark">
    <div class="container px-5">
        <div class="row gx-5 justify-content-center">
            <div class="col-lg-6">
                <div class="text-center my-5">
                    <h1 class="display-5 fw-bolder text-white mb-2">Django Pet</h1>
                    <p class="lead text-white-50 mb-4">Sistema de Gestión de Mascotas</p>
                </div>
            </div>
        </div>
    </div>
</header>
<!-- Features section-->
{% block content %}{% endblock %}

<!-- Footer-->
<footer class="py-5 bg-dark">
    <div class="container px-5"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2023</p></div>
</footer>
<!-- Bootstrap core JS-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
<!-- Core theme JS-->
<script src="{% static 'js/script.js' %}"></script>
<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
<!-- * *                               SB Forms JS                               * *-->
<!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
<script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
</body>
</html>